### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by akissa**

### CODE REVIEW

**Comment by kaukas** [comment]
I can see you spent a lot of time on the improvement. Unfortunately I am out of context and not using this project any more. For these reasons I can not maintain it any longer. If anyone would like to take over maintenance I'd be happy to pass it over.

**Comment by akissa** [comment]
I would be happy to maintain the project going forward.

**Comment by kaukas** [comment]
I tried to transfer the repository to you but Github complains that `akissa/repoze.who-use_beaker already` exists. Could you please rename your local repository to something else?

**Comment by akissa** [comment]
I have renamed it, if possibly please transfer the pypi as well. My pypi username is topdog

**Comment by kaukas** [comment]
Github still complains:

```
akissa already has a repository in the kaukas/repoze.who-use_beaker network
```

I will try a bit later.

**Comment by akissa** [comment]
@kaukas  Thanks, the transfer has gone through

**Pull request merged**
